# Generated by Django 4.2.4 on 2023-09-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Messages', '0002_rename_chat_message_chat_id_alter_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_last_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Chat_Messages.chat'),
        ),
    ]
