# Generated by Django 4.2.4 on 2023-09-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Messages', '0003_rename_sender_first_name_message_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
