# Generated by Django 4.2.4 on 2023-08-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('password', models.CharField()),
                ('email', models.EmailField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
